constexpr byte NOP{0};
constexpr byte MOV{1};
constexpr byte JMP{2};
constexpr byte CMP{3};
constexpr byte MTH{4};
constexpr byte INT{5};
constexpr byte BIO{6};
constexpr byte STK{7};
constexpr byte PWR{8};
